


debug: false


# =================================
# spring
# =================================
spring:

  datasource:
    initialize: true
    url: jdbc:h2:mem:nkdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl_auto: none
        jdbc:
          batch_size: 20
