INSERT INTO INSERTABLE_ACCOUNT (ID, NAME) VALUES (1, 'nklee');
INSERT INTO INSERTABLE_ACCOUNT (ID, NAME) VALUES (2, 'nklee2');
INSERT INTO INSERTABLE_ACCOUNT (ID, NAME) VALUES (3, 'nklee3');

INSERT INTO UPDATABLE_HOTEL (ID, NAME, AGE) VALUES (1, '남규호텔', 11);
INSERT INTO UPDATABLE_HOTEL (ID, NAME, AGE) VALUES (2, '남규2호텔', 11);

INSERT INTO VERSION_MEMBER (ID, NAME, VERSION) VALUES (3, 'nklee', 0);

INSERT INTO OPTIMISTIC_MEMBER (ID, NAME, VERSION) VALUES (1, 'nklee', 0);


