INSERT INTO INSERTABLE_ACCOUNT (ID, NAME) VALUES (1, 'nklee');
INSERT INTO INSERTABLE_ACCOUNT (ID, NAME) VALUES (2, 'nklee2');
INSERT INTO INSERTABLE_ACCOUNT (ID, NAME) VALUES (3, 'nklee3');


INSERT INTO UPDATABLE_HOTEL (ID, NAME) VALUES (1, '남규호텔');
INSERT INTO UPDATABLE_HOTEL (ID, NAME) VALUES (2, '남규2호텔');

